### ISSUE TITLE
[Proposal] Map of structure in md file

### ISSUE THREAD

**Issue by zour228** [whsv26/notes#3]
What about adding some kind of top-level "Map" of file to fast review and navigate?

[See example](https://github.com/zour228/notes/blob/feature/referenced-map/LinuxCommands.md)

P.S.
This map may be auto generated by simple (php) script.
I've already wrote it, just not committed yet

**Comment by whsv26** [comment]
Top level header auto-referencing has been added.

`make` may link and generate notes from src/ to doc/ now.

**Comment by whsv26** [comment]
checkout **pandoc** package
